### ISSUE TITLE
Problem with MNV records in Mutect2 VCFs

### ISSUE THREAD

**Issue by eallen-bbi** [AlexandrovLab/SigProfilerClusters#10]
When the input VCF has rows with MNVs, then SigProfilerClusters crashes during subclassification of clustered mutations.  Example VCF row excerpt and error message are copied below:

VCF file:
chr9	534258	.	GT	CC	.	PASS

err log file:
Traceback (most recent call last):
  File "/home/eallen/miniconda3/lib/python3.8/site-packages/SigProfilerClusters/classifyFunctions.py", line 237, in pullVaf
    vaf = vafs[sample][newKey]
KeyError: '9:534258:G:C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eallen/miniconda3/lib/python3.8/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 685, in analysis
    classifyFunctions.pullVaf (project, input_path, sanger, TCGA, standardVC, correction)
  File "/home/eallen/miniconda3/lib/python3.8/site-packages/SigProfilerClusters/classifyFunctions.py", line 240, in pullVaf
    vaf = vafs[sample][newKey]
KeyError: 'chr9:534258:G:C'

**Comment by ebergstr** [comment]
Hi,

Thank you for pointing out this limitation and apologies for the delay. We have now incorporated supported for single line MNVs. Please update your version of the tool to 1.0.11 to reflect these changes.

Best,
Erik

**Comment by eallen-bbi** [comment]
Great, thanks for the quick action.  Will try out in next 2-3 days and reply back on results.

**Comment by eallen-bbi** [comment]
OK, good news - the fix seems to have worked.  Ran on several samples without error.  Thanks again.
