### ISSUE TITLE
Finding the kataegic mutations using SigProfilerClusters

### ISSUE THREAD

**Issue by burcakotlu** [AlexandrovLab/SigProfilerClusters#30]
Dear all,

For the Mutographs ESCC 552 samples, I need to find the kataegic mutations and filter out them. Then, I need to carry out the strand-coordinated mutagenesis of SigProfilerTopography for the remaining mutations.

I have called SigProfilerClusters with the following commands:

###########################################
from SigProfilerClusters import SigProfilerClusters as hp

jobname = 'all_escc_552_samples'
genome = 'GRCh37'
contexts = '96'
simContext = ['96']
input_path = '/tscc/lustre/restricted/alexandrov-ddn/users/burcak/SigProfilerTopographyRuns/Mutographs_ESCC_552/all_escc_552_samples/'

hp.analysis(jobname, genome, contexts, simContext, input_path, subClassify=True, includedVAFs=False)
###########################################

However, I got the following error:

############################################
Traceback (most recent call last):
  File "/tscc/nfs/home/burcak/developer/SigProfilerTopographyRuns/Mutographs_ESCC_552/pbs_py_files/all_escc_552_samples_spc.py", line 10, in <module>
    hp.analysis(jobname, genome, contexts, simContext, input_path, subClassify=True, includedVAFs=False)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 1291, in analysis
    regions, imds = hotspot.hotSpotAnalysis(
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/SigProfilerClusters/hotspot.py", line 2328, in hotSpotAnalysis
    pp.savefig()
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/backends/backend_pdf.py", line 2766, in savefig
    figure.savefig(self, format="pdf", **kwargs)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/backends/backend_pdf.py", line 2807, in print_pdf
    self.figure.draw(renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/axis.py", line 1387, in draw
    ticks_to_draw = self._update_ticks()
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/axis.py", line 1275, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/axis.py", line 1495, in get_majorticklocs
    return self.major.locator()
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/ticker.py", line 2323, in __call__
    return self.tick_values(vmin, vmax)
  File "/tscc/nfs/home/burcak/.local/lib/python3.9/site-packages/matplotlib/ticker.py", line 2340, in tick_values
    raise ValueError(
ValueError: Data has no positive values, and therefore cannot be log-scaled.
############################################

How can we fix this issue? 
Is my command for running SigProfilerClusters incorrect? If yes, how should I call SigProfilerClusters?

Looking forward to your reply.

Best wishes,
Burcak

**Comment by MousumyCSE** [comment]
Hi Burcak,

As we communicated on email, hope you were able to solve your problems. Please re-open the issue if you encounter any other problems.

Best,
Mousumy
