### ISSUE TITLE
RuntimeError: process associated

### ISSUE THREAD

**Issue by shishuo16** [AlexandrovLab/SigProfilerClusters#5]
Hi,
SigProfilerClusters seems to be a very nice method for clustered mutation identification. However, when I run SigProfilerClusters with the example.vcf and code provided in "https://osf.io/qpmzw/wiki/5.%20Quick%20Start%20Example/". I got strange errors and the tool just kept running with no simulation output. 
my code:
`from SigProfilerMatrixGenerator import install as genInstall
from SigProfilerSimulator import SigProfilerSimulator as sigSim
from SigProfilerClusters import SigProfilerClusters as hp
sigSim.SigProfilerSimulator("BRCA", "./example/", "GRCh37", contexts = ['288'], chrom_based=True, simulations=100)
hp.analysis("BRCA", "GRCh37", "96", ["288"], "./example/", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, max_cpu=4, TCGA=True, sanger=False)`

The SigProfilerSimulator_BRCA_GRCh37_2022-03-28.err file:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/home/shuo.shi/APOBEC/SigProfiler/example.py", line 4, in <module>
    sigSim.SigProfilerSimulator("BRCA", "./example/", "GRCh37", contexts = ['288'], chrom_based=True, simulations=100)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/site-packages/SigProfilerSimulator/SigProfilerSimulator.py", line 413, in SigProfilerSimulator
    pool = mp.Pool(max_seed)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/share/home/shuo.shi/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

The SigProfilerSimulator_BRCA_GRCh37_2022-03-28.out file:
`THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME

-------System Info-------
Operating System Name: Linux
Nodename: gznode107
Release: 3.10.0-1127.el7.x86_64
Version: #1 SMP Tue Mar 31 23:36:51 UTC 2020

-------Python and Package Versions------- 
Python Version: 3.9.7
SigProfilerSimulator Version: 1.1.4
SigProfilerMatrixGenerator Version: 1.2.4
numpy version: 1.22.3

-------Vital Parameters Used for the execution -------
Project: BRCA
Genome: GRCh37
Input File Path: ./example/
contexts: ['288']
exome: None
simulations: 100
updating: False
bed_file: None
overlap: False
gender: female
seqInfo: False
chrom_based: True
seed_file: None

-------Date and Time Data------- 
Date and Clock time when the execution started: 2022-03-28 19:07:07.471765
`
However when I move "from SigProfilerClusters import SigProfilerClusters as hp" under the "sigSim.SigProfilerSimulator("BRCA", "./example/", "GRCh37", contexts = ['288'], chrom_based=True, simulations=100)", the sigSim.SigProfilerSimulator can run successly, but the next code hp.analysis will have the same kind of errors "RuntimeError: ......"
How can I fix it ?

**Comment by ebergstr** [comment]
The given error output appears to be an issue involved with the multiprocessing python package used on Windows (and linux) machines when running commands from within a script. Can I please ask you to try the example input from an interpreter (i.e. straight on command line/terminal)? 

Alternatively, if you are running the example code within a script, you can try adding the following: 
 

```
# All import functions
# Place here

if __name__ == '__main__':
     # All user code
     # Place here

```

**Comment by shishuo16** [comment]
```
# All import functions
# Place here

if __name__ == '__main__':
     # All user code
     # Place here
```

works fine. Thank you.
