### ISSUE TITLE
No such file or directory: '.output/simulations/data/imds.pickle'

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerClusters#7]
Hi. Thanks for developing and maintaining such a cool tool. 
I was running Clusters on my own data and I found an error log.
```
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lcj/.local/lib/python3.8/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 697, in analysis
    classifyFunctions.findClustersOfClusters_noVAF (project, chrom_based, input_path, windowSize, chromLengths, regions, log_file, genome, processors, imds, correction)
  File "/home/lcj/.local/lib/python3.8/site-packages/SigProfilerClusters/classifyFunctions.py", line 906, in findClustersOfClusters_noVAF
    with open(project_parent_path + "output/simulations/data/imds.pickle", "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '.output/simulations/data/imds.pickle'
```
**But I have checked my output/simulations/data/ folder and it included both imds.pickle and imds_corrected.pickle.** 

Below are the codes I used. The input file was a MAF.
```
sigSim.SigProfilerSimulator("MY_Project", ".", "GRCh38", contexts = ['1536'], chrom_based=True, simulations=100)
hp.analysis("MY_Project", "GRCh38", "96", ["1536"], ".", analysis="all", sortSims=True, calculateIMD=True, subClassify=True, max_cpu = 4, includedVAFs=False, includedCCFs=False)
```

Thanks.

**Comment by lincj1994** [comment]
And I just found a error log in the logs folder:
```
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lcj/.local/lib/python3.8/site-packages/SigProfilerClusters/SigProfilerClusters.py", line 697, in analysis
    classifyFunctions.findClustersOfClusters_noVAF (project, chrom_based, input_path, windowSize, chromLengths, regions, log_file, genome, processors, imds, correction)
  File "/home/lcj/.local/lib/python3.8/site-packages/SigProfilerClusters/classifyFunctions.py", line 906, in findClustersOfClusters_noVAF
    with open(project_parent_path + "output/simulations/data/imds.pickle", "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '.output/simulations/data/imds.pickle'
```

**Comment by lincj1994** [comment]
OK. I found it's because of the project path. It worked when using "./".

**Comment by lincj1994** [comment]
OK. I found it's because of the project path. It worked when using "./".
